services:
  server:
    build:
      context: .
      dockerfile: server.dockerfile
    volumes:
      - ../:/workdir
    tty: true
  client:
    build:
      context: .
      dockerfile: client.dockerfile
    volumes:
      - ./:/workdir
    entrypoint: /bin/bash
    tty: true
